// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2aebsonA3DDXR4MUteEWvl_piuCtAoTo',
    appId: '1:549286872426:web:9c12c053864facf2159113',
    messagingSenderId: '549286872426',
    projectId: 'sns-project-a',
    authDomain: 'sns-project-a.firebaseapp.com',
    storageBucket: 'sns-project-a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHXS1F2_b-1rc3OETerKIj23qRJFsLih0',
    appId: '1:549286872426:android:f87b8f9c928fa152159113',
    messagingSenderId: '549286872426',
    projectId: 'sns-project-a',
    storageBucket: 'sns-project-a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPgVBXkX604z3Z_ckfHC3gn-GCVt0I5Dg',
    appId: '1:549286872426:ios:978599d8a1e7b0e2159113',
    messagingSenderId: '549286872426',
    projectId: 'sns-project-a',
    storageBucket: 'sns-project-a.appspot.com',
    iosBundleId: 'com.example.tiktokPractice',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPgVBXkX604z3Z_ckfHC3gn-GCVt0I5Dg',
    appId: '1:549286872426:ios:b67b81b40d70b5f0159113',
    messagingSenderId: '549286872426',
    projectId: 'sns-project-a',
    storageBucket: 'sns-project-a.appspot.com',
    iosBundleId: 'com.example.tiktokPractice.RunnerTests',
  );
}
